src/apps/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [

    # Perfil de usuario
    url(
        regex=r'^profile/$',
        view=views.ProfileIndexView.as_view(),
        name='profile'
    ),
]

src/apps/authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'

urlpatterns = [

    # Muestra el formulario de registro.
    url(
        regex=r'^register/$',
        view=views.RegisterUserFormView.as_view(),
        name='register'
    ),

    # El registro ha sido satisfactorio.
    url(
        regex=r'^register/success/$',
        view=views.RegisterUserSuccessView.as_view(),
        name='success'
    ),

    # Valida un token.
    url(
        regex=r'^register/validate/(?P<token>[a-zA-Z0-9]{32})/$',
        view=views.RegisterUserValidateTokenView.as_view(),
        name='validate_token'
    ),

    # Formulario login.
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login'
    ),

    # Logout.
    url(
        regex=r'^logout/$',
        view=views.LogoutView.as_view(),
        name='logout'
    ),

    # Formulario cambiar contraseña.
    url(
        regex=r'^password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password_change'
    ),

    # Muestra mensaje cambio password ok.
    url(
        regex=r'^password-change/done/$',
        view=views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),

    # Restablecer contraseña (Contraseña olvidada).
    url(
        regex=r'^password-reset/$',
        view=views.PasswordResetView.as_view(),
        name='password_reset'
    ),

    # Informa al usuario que se ha mandado un email para restablecer la contraseña.
    url(
        regex=r'^password-reset/done/$',
        view=views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),

    # Verifica el token, se accede desde el email.
    # Si es correcto, mostrara un formulario para crear nueva contraseña.
    url(
        regex=(
            r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
            r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$'
        ),
        view=views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),

    # El token se ha verificado y muestra el resultado.
    url(
        regex=r'^reset/done/$',
        view=views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    # Actualizar el email.
    url(
        regex=r'^email/update/$',
        view=views.UserEmailUpdateView.as_view(),
        name='email_update'
    ),

    # Validación del token para cambiar el email.
    url(
        regex=r'^email/validate/(?P<token>[\w]{30})/$',
        view=views.UserEmailUpdateValidateView.as_view(),
        name='email_update_validate'
    ),

    # Token para cambiar email no existe.
    url(
        regex=r'^token/error/$',
        view=views.UserEmailUpdateNotFoundView.as_view(),
        name='token_email_not_exists'
    ),
]

src/apps/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [

    # /home/
    url(
        regex=r'^$',
        view=views.IndexView.as_view(),
        name='index'
    ),
]

src/apps/pages/urls.py
from django.conf.urls import url

from . import views

app_name = 'pages'

urlpatterns = [

    # Cookies Consent
    url(
        regex=r'^cookie-consent/$',
        view=views.CookieConsentView.as_view(),
        name='cookie_consent'
    ),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from home.views import IndexView

urlpatterns = [
    ##################################################
    # / Home page.
    url(r'^$', IndexView.as_view(), name='home_page'),
    ##################################################

    # /accounts/*
    url(r'^accounts/', include('accounts.urls')),

    # /auth/*
    url(r'^auth/', include('authentication.urls')),

    # /home/*
    url(r'^home/', include('home.urls')),

    # /pages/*
    url(r'^pages/', include('pages.urls')),

    # /admin/*
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    """Model para usuarios."""

    class Meta:
        verbose_name = _('Usuario')
        verbose_name_plural = _('Usuarios')

src/apps/accounts/views.py
from django.views import generic


class ProfileIndexView(generic.TemplateView):
    template_name = 'accounts/profile.html'

src/apps/authentication/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext as _
from django.views import generic

from utils.http import get_full_path
from utils.mail import send_templated_mail
from utils.mixins.views import AnonymousRequiredMixin

from .forms import AuthenticationForm, RegisterUserForm, UserEmailUpdateForm
from .models import RegisterUser, UserEmailUpdate
from .utils import delete_expired_registers

UserModel = get_user_model()


class RegisterUserFormView(AnonymousRequiredMixin, generic.CreateView):
    """Muestra el formulario de registro."""
    template_name = 'authentication/register.html'
    form_class = RegisterUserForm
    model = RegisterUser

    def __init__(self, *args, **kwargs):
        """Elimina posibles usuarios expirados."""
        delete_expired_registers()
        super().__init__(*args, **kwargs)

    def get_success_url(self):
        """Si todo OK, envia el email para verificación y direcciona."""
        self._send_email_with_token()
        return reverse('authentication:success')

    def _send_email_with_token(self):
        """Envía un email con token para terminar proceso de registro."""
        current_site = get_current_site(self.request)
        site_name = current_site.name
        url_validate_token = get_full_path(
            self.request,
            'authentication:validate_token',
            token=self.object.token
        )
        context = {
            'username': self.object.username,
            'email': self.object.email,
            'site_name': site_name,
            'url_validate_token': url_validate_token
        }
        send_templated_mail(
            subject=_('Validación de email en {}').format(site_name),
            from_email=settings.GROUP_EMAILS['NO-REPLY'],
            recipients=[self.object.email],
            context=context,
            template_text='authentication/emails/register_success.txt'
        )


class RegisterUserSuccessView(AnonymousRequiredMixin, generic.TemplateView):
    template_name = 'authentication/success.html'


class RegisterUserValidateTokenView(AnonymousRequiredMixin, generic.TemplateView):
    """Validación email de un nuevo registro a través del token."""
    template_name = 'authentication/validate_token.html'

    def get(self, request, *args, **kwargs):
        delete_expired_registers()
        token = self.kwargs.get('token')
        try:
            user_temp = RegisterUser.objects.get(token=token)
        except RegisterUser.DoesNotExist:
            return render(request, 'authentication/token_not_exists.html')
        self._move_user_temp_to_user(user_temp)
        return super().get(request, *args, **kwargs)

    def _move_user_temp_to_user(self, user_temp):
        """Mueve usuario temporal a auth_user y elimina el temporal."""
        user_model = UserModel.objects.create(
            username=user_temp.username,
            email=user_temp.email,
            password=user_temp.password
        )
        if user_model:
            user_temp.delete()


class LoginView(AnonymousRequiredMixin, views.LoginView):
    template_name = 'authentication/login.html'
    form_class = AuthenticationForm


class LogoutView(LoginRequiredMixin, views.LogoutView):
    template_name = 'authentication/logged_out.html'


class PasswordResetView(AnonymousRequiredMixin, views.PasswordResetView):
    template_name = 'authentication/password_reset_form.html'
    email_template_name = 'authentication/emails/password_reset_email.html'
    subject_template_name = 'authentication/emails/password_reset_subject.txt'
    success_url = reverse_lazy('authentication:password_reset_done')


class PasswordResetDoneView(AnonymousRequiredMixin, views.PasswordResetDoneView):
    template_name = 'authentication/password_reset_done.html'


class PasswordResetConfirmView(AnonymousRequiredMixin, views.PasswordResetConfirmView):
    template_name = 'authentication/password_reset_confirm.html'
    success_url = reverse_lazy('authentication:password_reset_complete')


class PasswordResetCompleteView(AnonymousRequiredMixin, views.PasswordResetCompleteView):
    template_name = 'authentication/password_reset_complete.html'


class PasswordChangeView(views.PasswordChangeView):
    template_name = 'authentication/password_change_form.html'
    success_url = reverse_lazy('authentication:password_change_done')


class PasswordChangeDoneView(views.PasswordChangeDoneView):
    template_name = 'authentication/password_change_done.html'


class UserEmailUpdateView(LoginRequiredMixin, generic.FormView):
    """Muestra el formulario para cambiar el email."""
    template_name = 'authentication/email_update.html'
    form_class = UserEmailUpdateForm
    model = UserEmailUpdate

    def get_initial(self):
        """Establece datos en los campos del form."""
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['token'] = self._generate_unique_token()
        initial['new_email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        """Enviá el email de confirmación."""
        new_email = form.cleaned_data['new_email']
        token = form.cleaned_data['token']
        self._update_or_create_model(token, new_email)
        self._send_confirm_email_for_validate(token, new_email)
        return super().form_valid(form)

    def get_success_url(self):
        msg = _('Se ha enviado un email a la nueva dirección para la confirmación')
        messages.success(self.request, msg)
        return reverse('accounts:profile')

    def _generate_unique_token(self):
        """Genera un token único.

        Comprueba que no exista uno igual en la db.

        Returns:
            str: Token generado de 30 caracteres.
        """
        while True:
            token = get_random_string(length=30)
            if not UserEmailUpdate.objects.filter(token=token):
                return token

    def _update_or_create_model(self, token, new_email):
        """Crear o actualiza un nuevo email en UserEmailUpdate."""
        UserEmailUpdate.objects.update_or_create(
            defaults={'new_email': new_email, 'token': token},
            user=self.request.user
        )

    def _send_confirm_email_for_validate(self, token, new_email):
        """Enviá un email para la confirmación del nuevo email con un token."""
        current_site = get_current_site(self.request)
        url_validate_token = get_full_path(
            self.request,
            'authentication:email_update_validate',
            token=token
        )
        context = {
            'url_validate_token': url_validate_token,
            'site_name': current_site.name
        }
        send_templated_mail(
            subject=_('Confirmación cambio de email'),
            from_email=settings.GROUP_EMAILS['NO-REPLY'],
            recipients=[new_email],
            context=context,
            template_text='authentication/emails/email_update_confirm.txt'
        )


class UserEmailUpdateValidateView(LoginRequiredMixin, generic.View):
    """Verifica el token de cambio de email.

    Para mayor seguridad, el usuario ha de estar logueado.

    Una vez comprobado y actualizado el nuevo email, elimina el
    email temporal.
    """

    def get(self, request, *args, **kwargs):
        """Comprueba el token que coincida."""
        token = kwargs.get('token')
        try:
            email_update = UserEmailUpdate.objects.get(token=token, user=request.user)
        except UserEmailUpdate.DoesNotExist:
            return redirect('authentication:token_email_not_exists')
        self.request.user.email = email_update.new_email
        self.request.user.save()
        email_update.delete()
        messages.success(request, _('Se ha actualizado el email'))
        return redirect(reverse('accounts:profile'))


class UserEmailUpdateNotFoundView(generic.TemplateView):
    """El token no existe o no pertenece al usuario."""
    template_name = 'authentication/token_email_not_exists.html'

src/apps/home/views.py
from django.contrib import messages
from django.views import generic


class IndexView(generic.TemplateView):
    """Pagina de prueba para home."""
    template_name = 'home/index.html'

    def get(self, request, *args, **kwargs):
        """Prueba de messages."""
        messages.info(request, 'Three credits remain in your account.')
        messages.success(request, 'Profile details updated.')
        messages.warning(request, 'Your account expires in three days.')
        messages.error(request, 'Document deleted.')
        return super().get(request, *args, **kwargs)

src/apps/pages/views.py
from django.contrib.sites.models import Site
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.views import generic


class PageMixin(object):
    """Mixin para pages.

    Variables de clase:
    * template_name: Template .html (requerido)
    * template_md: Template .md (no requerido)
    * context_md: Contexto para templates *.md

    Requiere una URLConf para cada vista.

    Si no tiene valor template_md, simplemente renderiza
    la pagina .html.

    get_context_md similar a get_context_data pero para template_md.
    """
    template_md = None
    context_md = {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.template_md:
            try:
                context['template_md'] = get_template(self.template_md).render(
                    self.get_context_md()
                )
            except TemplateDoesNotExist:
                raise TemplateDoesNotExist('Template {} no existe'.format(self.template_md))
        return context

    def get_context_md(self):
        """Similar a get_context_data pero para el *.md."""
        return self.context_md

# EXAMPLE:
# class AboutView(PageMixin, generic.TemplateView):
#     template_name = 'pages/hello.html'
#     template_md = 'pages/hello.md'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['nombre'] = 'Perico palote'
#         return context
#
#     def get_context_md(self):
#         context = super().get_context_md()
#         context['hola'] = 'Hello world'
#         return context


class CookieConsentView(PageMixin, generic.TemplateView):
    """Muestra la politica de cookies."""
    template_name = 'pages/cookie_consent.html'
    template_md = 'pages/cookie_consent.md'

    def get_context_md(self):
        context = super().get_context_md()
        context['site'] = Site.objects.get_current()
        return context

src/apps/utils/mixins/views.py
from django.conf import settings
from django.shortcuts import Http404, redirect


class AnonymousRequiredMixin(object):
    """Mixin para autorizar solo a usuarios anónimos."""

    def dispatch(self, request, *args, **kwargs):
        """Comprueba que sea un usuario anónimo.

        Si no es un usuario anónimo, lo redirecciona a la
        pagina LOGIN_REDIRECT_URL.
        """
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)


class SuperuserRequiredMixin(object):
    """Solo un superuser puede visitar la pagina."""

    def dispatch(self, request, *args, **kwargs):
        """Si el usuario no esta logueado también lanza Http404."""
        if not request.user.is_authenticated or not request.user.is_superuser:
            raise Http404
        return super().dispatch(request, *args, **kwargs)


class OwnerOrSuperuserRequiredMixin(object):
    """Solo el owner y superuser puede ver la view.

    Requiere un usuario autenticado.

    Requiere de un campo 'owner_field', que sera el campo a comprobar.
    Por defecto owner_field = 'owner'.
    """
    owner_field = 'owner'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        obj_owner = getattr(obj, self.owner_field)
        if not obj_owner:
            raise NotImplementedError('El campo {} no existe'.format(self.owner_field))
        user = request.user
        if not user.is_authenticated or obj_owner != user and not user.is_superuser:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

src/templates/_cookieconsent.html
{% load i18n %}

<!-- https://cookieconsent.insites.com/ -->
<script>
  window.addEventListener("load", function(){
  window.cookieconsent.initialise({
    "palette": {
      "popup": {
        "background": "#252e39"
      },
      "button": {
        "background": "transparent",
        "text": "#14a7d0",
        "border": "#14a7d0"
      }
    },
    "content": {
      "message": "{% trans 'Usamos cookies propias y de terceros para mejorar tu experiencia y realizar tareas de analítica.' %}",
      "dismiss": "{% trans 'De acuerdo' %}",
      "link": "{% trans 'Leer mas' %}",
      "href": "/pages/cookie-consent/"
    }
  })});
</script>

src/templates/_footer.html
<footer class="footer">
  <section class="container">
    <div class="row">
      <div class="col-md-6 col-lg-4">
        <ul class="list-unstyled links">
          {# Todos los usuarios #}
          <li>
            <a href="#">
              <i class="material-icons">add</i> Añadir algo
            </a>
          </li>

          {# Usuarios logueados #}
          {% if user.is_authenticated %}
            <li>
              <a href="{% url 'accounts:profile' %}">
                <i class="material-icons">person</i> Mi cuenta
              </a>
            </li>
            <li>
              <a href="{% url 'authentication:logout' %}">
                <i class="material-icons">exit_to_app</i> Terminar sesión
              </a>
            </li>
          {% else %}
            {# Usuarios anónimos #}
            <li>
              <a href="{% url 'authentication:login' %}?next={{ request.get_full_path }}">
                <i class="material-icons">person</i> Iniciar sesión
              </a>
            </li>
            <li>
              <a href="{% url 'authentication:register' %}">
                <i class="material-icons">person_add</i> Registrar
              </a>
            </li>
          {% endif %}
        </ul>
      </div>

      <div class="col-md-6 col-lg-4">
        <ul class="list-unstyled links">
          <li><a href="#">Lorem ipsum</a></li>
          <li><a href="#">Lorem ipsum</a></li>
          <li><a href="#">Lorem ipsum</a></li>
          <li><a href="#">Lorem ipsum</a></li>
          <li><a href="#">Lorem ipsum</a></li>
        </ul>
      </div>

      <div class="col-md-6 col-lg-4">
        <!-- Compartir con las redes -->
        <section class="row mt-4">
          <div class="col-12">
            <div class="share-icons">
              <a class="facebook" onclick="window.open('http://www.facebook.com/sharer/sharer.php?u={{ PROTOCOL }}{{ request.get_host }}&amp;title={{ SITE.name }}', '', 'width=500,height=300');">
                <i class="fa fa-facebook-official" aria-hidden="true"></i>
              </a>
              <a class="gplus" onclick="window.open('https://plus.google.com/share?url={{ PROTOCOL }}{{ request.get_host }}', '', 'width=500,height=300');">
                <i class="fa fa-google-plus-official" aria-hidden="true"></i>
              </a>
              <a class="twitter" onclick="window.open('http://twitter.com/intent/tweet?status={{ SITE.name }}+{{ PROTOCOL }}{{ request.get_host }}', '', 'width=500,height=300');">
                <i class="fa fa-twitter-square" aria-hidden="true"></i>
              </a>
              <a class="twitter" onclick="window.open('http://www.linkedin.com/shareArticle?mini=true&amp;url={{ PROTOCOL }}{{ request.get_host }}&amp;title={{ SITE.name }}&amp;source={{ SITE.domain }}', '', 'width=500,height=300');">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </section><!-- Compartir con las redes -->
      </div>
    </div>
  </section>

  <section class="row copy">
    <div class="col-12">
      <section class="container">
        &copy; 2017-{% now "Y" %} {{ SITE.domain }} - Salvador Nicolas &lt;snicoper@gmail.com&gt;
      </section>
    </div>
  </section>
</footer>

src/templates/_header.html
{% load staticfiles %}

<nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-primary">
  <button class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="{% url 'home_page' %}">
    <img class="d-inline-block align-top"
         src="{% static 'logo.png' %}"
         alt="{{ SITE.name }} Logo"
         height="30">
    {{ SITE.name }}
  </a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>

    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
             href="{% url 'accounts:profile' %}"
             id="navbarDropdownMenuLink"
             data-toggle="dropdown"
             aria-haspopup="true"
             aria-expanded="false"
          >
            <i class="material-icons">person</i> {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'accounts:profile' %}">
              <i class="material-icons">person</i> Mi cuenta
            </a>
            <a class="dropdown-item" href="{% url 'authentication:logout' %}">
              <i class="material-icons">exit_to_app</i> Terminar sesión
            </a>
          </div>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:register' %}">
            <i class="material-icons">person_add</i> Registro
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authentication:login' %}">
            <i class="material-icons">person</i> Iniciar sesión
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

src/templates/_messages.html
{% for message in messages %}
  <script>
    toastr['{{ message.tags }}']('{{ message }}');
  </script>
{% endfor %}

src/templates/_pagination.html
{% load utils_tags %}

{% if page_obj.paginator.page_range|length > 1 %}
  <section class="row">
    <div class="col-12">
      <nav class="mt-2">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="{% previous_pagination %}">
                <i class="material-icons md-3">keyboard_arrow_left</i> Anterior
              </a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">
                <i class="material-icons md-3">keyboard_arrow_left</i> Anterior
              </a>
            </li>
          {% endif %}

          <li class="page-item disabled">
            <a class="page-link" href="javascript:void(0);">
              {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
            </a>
          </li>

          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="{% next_pagination %}">
                Siguiente <i class="material-icons md-3">keyboard_arrow_right</i>
              </a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#">
                Siguiente <i class="material-icons md-3">keyboard_arrow_right</i>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </section>
{% endif %}

src/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{% block meta_description %}{% endblock meta_description %}">
  <meta name="keywords" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
  <title>{{ SITE.name }} {% block head_title %}{% endblock head_title %}</title>
  <!-- default css -->
  {% if debug %}
    <link href="{% static 'dist/css/main.css' %}" rel="stylesheet">
  {% else %}
    <link href="{% static 'dist/css/main.min.css' %}" rel="stylesheet">
  {% endif %}

  <!-- extras en header -->
  {% block extra_heads %}{% endblock extra_heads %}
</head>
<body>
  <!-- header -->
  {% block header %}
    {% include "_header.html" %}
  {% endblock header %}<!-- end header -->

  <!-- content -->
  <main>
    <!-- Titulo de la pagina -->
    {% block page_title %}{% endblock page_title %}

    <!-- Contenido principal -->
    {% block content %}{% endblock content %}
  </main><!-- end content -->

  <!-- footer -->
  {% block footer %}
    {% include "_footer.html" %}
  {% endblock footer %}<!-- end footer -->

  <!-- Boton de subir, solo se muestra en resoluciones >= tablets -->
  <div class="to-top hidden-sm-down"></div>

  <!-- cookieconsent -->
  {% include "_cookieconsent.html" %}

  <!-- default js -->
  {% if debug %}
    <script src="{% static 'dist/js/vendor.js' %}"></script>
    <script src="{% static 'dist/js/main.js' %}"></script>
  {% else %}
    <script src="{% static 'dist/js/vendor.min.js' %}"></script>
    <script src="{% static 'dist/js/main.min.js' %}"></script>
  {% endif %}

  <!-- mensajes -->
  {% if messages %}
    {% include "_messages.html" %}
  {% endif %}

  <!-- scripts -->
  {% block scripts %}{% endblock scripts %}
</body>
</html>